print("Connecting to server NATO")
print("HACK auth servers")
print("HACK main servers")
print("............")
print("HACK Completed!!!")
print("HACK again")
print("............")
print("............")
print("............")
print("............")
print("............")